[project]
name = "gtex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"numpy==2.0.2",
	"pandas==2.2.3",
	"python-dateutil==2.9.0.post0",
	"pytz==2025.1",
	"six==1.17.0",
	"tzdata==2024.2",
]
